name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -race -v ./...

    - name: Test
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_FILE_PATH: ${{ secrets.TELEGRAM_FILE_PATH }}
        TELEGRAM_FILE_ID: ${{ secrets.TELEGRAM_FILE_ID }}
      run: |
        wget https://www.w3.org/People/mimasa/test/imgformat/img/w3c_home.jpg
        go test -v ./...
